"""
core/database.py — All SQLite operations for the Mock Interview Stress Tester.

This module is the single source of truth for every database interaction in
the project.  No other file may import sqlite3 or issue SQL directly.

Schema
------
sessions
    session_id   TEXT PRIMARY KEY   — UUID generated by the orchestrator
    company      TEXT NOT NULL       — company name entered by the user
    role         TEXT NOT NULL       — job role entered by the user
    level        TEXT NOT NULL       — experience level entered by the user
    state        TEXT NOT NULL       — current orchestrator state label
    created_at   TEXT NOT NULL       — ISO-8601 timestamp (UTC)

research
    session_id   TEXT PRIMARY KEY   — FK → sessions.session_id
    data         TEXT NOT NULL       — JSON-serialised Researcher dict (8 keys)

questions
    session_id   TEXT NOT NULL       — FK → sessions.session_id
    q_index      INTEGER NOT NULL    — 0-based position in the 10-question list
    data         TEXT NOT NULL       — JSON-serialised Question_Dict entry
    PRIMARY KEY (session_id, q_index)

answers
    session_id   TEXT NOT NULL       — FK → sessions.session_id
    q_index      INTEGER NOT NULL    — which question this answer belongs to
    answer_text  TEXT NOT NULL       — raw user answer text
    evaluation   TEXT NOT NULL       — JSON-serialised Evaluation_Dict (6 keys)
    answered_at  TEXT NOT NULL       — ISO-8601 timestamp (UTC)
    PRIMARY KEY (session_id, q_index)

reports
    session_id   TEXT PRIMARY KEY   — FK → sessions.session_id
    data         TEXT NOT NULL       — JSON-serialised Coach dict (11 keys)
    created_at   TEXT NOT NULL       — ISO-8601 timestamp (UTC)

Public functions (8 total)
--------------------------
init_db()
create_session(session_id, company, role, level)
get_session(session_id)
save_research(session_id, research_dict)
save_questions(session_id, questions_list)
save_answer(session_id, q_index, answer_text, evaluation_dict)
get_answers(session_id)
save_report(session_id, report_dict)
"""

import json
import sqlite3
from datetime import datetime, timezone

from core.config import DB_PATH

# ---------------------------------------------------------------------------
# Private helper
# ---------------------------------------------------------------------------


def _get_connection() -> sqlite3.Connection:
    """Open and return a new SQLite connection to DB_PATH.

    The connection is configured with:
    - ``check_same_thread=False`` so that Streamlit (which may access the
      connection from multiple threads) does not raise an error.
    - ``isolation_level=None`` (autocommit) is NOT set here; callers use the
      context-manager form ``with conn:`` to commit/rollback atomically.

    Returns:
        A ``sqlite3.Connection`` instance ready for use.
    """
    return sqlite3.connect(DB_PATH, check_same_thread=False)


def _now_iso() -> str:
    """Return the current UTC time as an ISO-8601 string.

    Format: ``YYYY-MM-DDTHH:MM:SS.ffffff+00:00``

    Returns:
        Current UTC datetime formatted as an ISO-8601 string with timezone info.
    """
    return datetime.now(timezone.utc).isoformat()


# ---------------------------------------------------------------------------
# Public functions
# ---------------------------------------------------------------------------


def init_db() -> None:
    """Create all database tables if they do not already exist.

    Safe to call multiple times (uses ``CREATE TABLE IF NOT EXISTS``).
    Creates five tables: ``sessions``, ``research``, ``questions``,
    ``answers``, and ``reports``.  See module docstring for the full schema.

    Returns:
        None

    Raises:
        sqlite3.Error: If the database file cannot be opened or the DDL
            statements fail for any reason.
    """
    conn = _get_connection()
    with conn:
        conn.execute("""
            CREATE TABLE IF NOT EXISTS sessions (
                session_id    TEXT PRIMARY KEY,
                company       TEXT NOT NULL,
                role          TEXT NOT NULL,
                level         TEXT NOT NULL,
                state         TEXT NOT NULL,
                num_questions INTEGER NOT NULL DEFAULT 5,
                created_at    TEXT NOT NULL
            )
        """)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS research (
                session_id  TEXT PRIMARY KEY,
                data        TEXT NOT NULL
            )
        """)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS questions (
                session_id  TEXT NOT NULL,
                q_index     INTEGER NOT NULL,
                data        TEXT NOT NULL,
                PRIMARY KEY (session_id, q_index)
            )
        """)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS answers (
                session_id   TEXT NOT NULL,
                q_index      INTEGER NOT NULL,
                answer_text  TEXT NOT NULL,
                evaluation   TEXT NOT NULL,
                answered_at  TEXT NOT NULL,
                PRIMARY KEY (session_id, q_index)
            )
        """)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS reports (
                session_id  TEXT PRIMARY KEY,
                data        TEXT NOT NULL,
                created_at  TEXT NOT NULL
            )
        """)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS follow_up_tracking (
                session_id  TEXT NOT NULL,
                q_index     INTEGER NOT NULL,
                count       INTEGER NOT NULL DEFAULT 0,
                PRIMARY KEY (session_id, q_index)
            )
        """)
        # Migration: add category column to answers table for existing DBs
        try:
            conn.execute("ALTER TABLE answers ADD COLUMN category TEXT NOT NULL DEFAULT ''")
        except Exception:
            pass  # column already exists on fresh DB, safe to ignore
    conn.close()


def create_session(
    session_id: str,
    company: str,
    role: str,
    level: str,
    num_questions: int = 5,
) -> None:
    """Insert a new session row into the ``sessions`` table.

    The initial state is always ``STATE_SETUP`` (imported from config).
    ``created_at`` is set to the current UTC time.

    Args:
        session_id: UUID string generated by the orchestrator for this session.
        company: Company name as entered by the user.
        role: Job role as entered by the user.
        level: Experience level as entered by the user (e.g. "junior", "senior").
        num_questions: Number of questions for this session (2–15).

    Returns:
        None

    Raises:
        sqlite3.IntegrityError: If a session with the same ``session_id``
            already exists (PRIMARY KEY violation).
        sqlite3.Error: On any other database error.
    """
    from core.config import STATE_SETUP  # local import avoids circular dependency at module level
    conn = _get_connection()
    with conn:
        conn.execute(
            """
            INSERT INTO sessions (session_id, company, role, level, state, num_questions, created_at)
            VALUES (?, ?, ?, ?, ?, ?, ?)
            """,
            (session_id, company, role, level, STATE_SETUP, num_questions, _now_iso()),
        )
    conn.close()


def get_session(session_id: str) -> dict | None:
    """Fetch a session row by its ``session_id``.

    Args:
        session_id: UUID string identifying the session to retrieve.

    Returns:
        A dict with keys ``session_id``, ``company``, ``role``, ``level``,
        ``state``, ``created_at`` if the row exists, or ``None`` if no
        matching row is found.

    Raises:
        sqlite3.Error: On any database error.
    """
    conn = _get_connection()
    conn.row_factory = sqlite3.Row
    cursor = conn.execute(
        "SELECT session_id, company, role, level, state, num_questions, created_at "
        "FROM sessions WHERE session_id = ?",
        (session_id,),
    )
    row = cursor.fetchone()
    conn.close()
    if row is None:
        return None
    return dict(row)


def save_research(session_id: str, research_dict: dict) -> None:
    """Persist the Researcher agent's output for a session.

    Uses ``INSERT OR REPLACE`` so calling this function a second time for
    the same session overwrites the previous research data (idempotent).

    The ``research_dict`` must conform to the 8-key Researcher contract
    defined in anti-hallucination.md:
    ``{company, role, interview_rounds, key_topics, difficulty,
    culture_keywords, known_question_types, red_flags_to_test}``

    Args:
        session_id: UUID string identifying the owning session.
        research_dict: Validated Researcher output dict with exactly 8 keys.

    Returns:
        None

    Raises:
        ValueError: If ``research_dict`` is missing any of the 8 required keys.
        sqlite3.Error: On any database error.
    """
    required = {
        "company", "role", "interview_rounds", "key_topics",
        "difficulty", "culture_keywords", "known_question_types", "red_flags_to_test",
    }
    missing = required - set(research_dict.keys())
    if missing:
        raise ValueError(f"save_research: missing keys in research_dict: {missing}")

    conn = _get_connection()
    with conn:
        conn.execute(
            "INSERT OR REPLACE INTO research (session_id, data) VALUES (?, ?)",
            (session_id, json.dumps(research_dict)),
        )
    conn.close()


def save_questions(session_id: str, questions_list: list[dict]) -> None:
    """Persist all generated questions for a session.

    Each element of ``questions_list`` is one Question_Dict entry from the
    QuestionGenerator output (keys: ``id, category, question, ideal_keywords,
    difficulty, follow_ups, scoring_hint``).

    Rows are inserted with their list position as ``q_index`` (0-based).
    Uses ``INSERT OR REPLACE`` per row so the call is idempotent.

    Args:
        session_id: UUID string identifying the owning session.
        questions_list: List of question dicts (2–15 items),
            each conforming to the QuestionGenerator 7-key contract.

    Returns:
        None

    Raises:
        ValueError: If ``questions_list`` is empty, or if any item is missing required keys.
        sqlite3.Error: On any database error.
    """
    from core.config import MIN_QUESTIONS, MAX_QUESTIONS  # local import; avoids potential circular refs
    if not questions_list or len(questions_list) < MIN_QUESTIONS or len(questions_list) > MAX_QUESTIONS:
        raise ValueError(
            f"save_questions: expected {MIN_QUESTIONS}-{MAX_QUESTIONS} questions, got {len(questions_list)}"
        )
    required = {"id", "category", "question", "ideal_keywords", "difficulty", "follow_ups", "scoring_hint"}
    for i, q in enumerate(questions_list):
        missing = required - set(q.keys())
        if missing:
            raise ValueError(f"save_questions: question[{i}] missing keys: {missing}")

    conn = _get_connection()
    with conn:
        for q_index, q in enumerate(questions_list):
            conn.execute(
                """
                INSERT OR REPLACE INTO questions (session_id, q_index, data)
                VALUES (?, ?, ?)
                """,
                (session_id, q_index, json.dumps(q)),
            )
    conn.close()


def save_answer(
    session_id: str,
    q_index: int,
    answer_text: str,
    evaluation_dict: dict,
    category: str = "",
) -> None:
    """Persist a user's answer and its evaluated result for one question.

    Uses ``INSERT OR REPLACE`` so re-evaluating an answer (e.g. after a
    follow-up) replaces the previous row for the same ``(session_id, q_index)``.

    The ``evaluation_dict`` must conform to the 6-key Evaluator contract
    defined in anti-hallucination.md:
    ``{scores, total, verdict, feedback, missing_keywords, trigger_follow_up}``

    Args:
        session_id: UUID string identifying the owning session.
        q_index: Zero-based index of the question being answered (0–9).
        answer_text: The raw answer text submitted by the user.
        evaluation_dict: Validated Evaluator output dict with exactly 6 keys.
        category: The question category (e.g. "technical", "behavioral").

    Returns:
        None

    Raises:
        ValueError: If ``evaluation_dict`` is missing any of the 6 required keys.
        sqlite3.Error: On any database error.
    """
    required = {"scores", "total", "verdict", "feedback", "missing_keywords", "trigger_follow_up"}
    missing = required - set(evaluation_dict.keys())
    if missing:
        raise ValueError(f"save_answer: missing keys in evaluation_dict: {missing}")

    conn = _get_connection()
    with conn:
        conn.execute(
            """
            INSERT OR REPLACE INTO answers
                (session_id, q_index, answer_text, evaluation, category, answered_at)
            VALUES (?, ?, ?, ?, ?, ?)
            """,
            (
                session_id,
                q_index,
                answer_text,
                json.dumps(evaluation_dict),
                category,
                _now_iso(),
            ),
        )
    conn.close()


def get_answers(session_id: str) -> list[dict]:
    """Retrieve all stored answers for a session, ordered by question index.

    Called by the Coach agent to build the compressed answer summary needed
    for the final report prompt.

    Args:
        session_id: UUID string identifying the owning session.

    Returns:
        A list of dicts ordered by ``q_index`` ascending.  Each dict has keys:
        ``q_index`` (int), ``answer_text`` (str), ``evaluation`` (dict —
        the deserialised Evaluation_Dict), ``answered_at`` (str ISO-8601).
        Returns an empty list if no answers exist for the session.

    Raises:
        sqlite3.Error: On any database error.
    """
    conn = _get_connection()
    conn.row_factory = sqlite3.Row
    cursor = conn.execute(
        "SELECT q_index, answer_text, evaluation, category, answered_at "
        "FROM answers WHERE session_id = ? ORDER BY q_index ASC",
        (session_id,),
    )
    rows = cursor.fetchall()
    conn.close()
    result = []
    for row in rows:
        result.append({
            "q_index": row["q_index"],
            "answer_text": row["answer_text"],
            "evaluation": json.loads(row["evaluation"]),
            "category": row["category"],
            "answered_at": row["answered_at"],
        })
    return result


def save_report(session_id: str, report_dict: dict) -> None:
    """Persist the Coach agent's final report for a session.

    Uses ``INSERT OR REPLACE`` so regenerating a report overwrites the
    previous one (idempotent).

    The ``report_dict`` must conform to the 11-key Coach contract defined in
    anti-hallucination.md:
    ``{overall_score, hiring_probability, hiring_probability_percent,
    strongest_category, weakest_category, category_averages,
    top_3_strengths, top_3_improvements, critical_moment,
    overall_verdict, next_interview_tip}``

    Args:
        session_id: UUID string identifying the owning session.
        report_dict: Validated Coach output dict with exactly 11 keys.

    Returns:
        None

    Raises:
        ValueError: If ``report_dict`` is missing any of the 11 required keys.
        sqlite3.Error: On any database error.
    """
    required = {
        "overall_score", "hiring_probability", "hiring_probability_percent",
        "strongest_category", "weakest_category", "category_averages",
        "top_3_strengths", "top_3_improvements", "critical_moment",
        "overall_verdict", "next_interview_tip",
    }
    missing = required - set(report_dict.keys())
    if missing:
        raise ValueError(f"save_report: missing keys in report_dict: {missing}")

    conn = _get_connection()
    with conn:
        conn.execute(
            """
            INSERT OR REPLACE INTO reports (session_id, data, created_at)
            VALUES (?, ?, ?)
            """,
            (session_id, json.dumps(report_dict), _now_iso()),
        )
    conn.close()


def update_session_state(session_id: str, new_state: str) -> None:
    """Update the state field for an existing session.

    Executes an UPDATE on the ``sessions`` table setting ``state`` to the
    provided value.  If no row matches the given ``session_id`` the function
    raises a ValueError (the session does not exist).

    Args:
        session_id: UUID string identifying the session to update.
        new_state: The new state label to persist (one of the STATE_*
            constants from ``core/config``).

    Returns:
        None

    Raises:
        ValueError: If no session with the given ``session_id`` exists
            (i.e. ``cursor.rowcount == 0`` after the UPDATE).
        sqlite3.Error: On any other database error.
    """
    conn = _get_connection()
    with conn:
        cursor = conn.execute(
            "UPDATE sessions SET state = ? WHERE session_id = ?",
            (new_state, session_id),
        )
    if cursor.rowcount == 0:
        conn.close()
        raise ValueError(
            f"update_session_state: no session found with session_id={session_id}"
        )
    conn.close()


def get_question(session_id: str, q_index: int) -> dict | None:
    """Retrieve a single question by session and index.

    Looks up the ``questions`` table by the composite key
    ``(session_id, q_index)`` and JSON-deserializes the stored data.

    Args:
        session_id: UUID string identifying the owning session.
        q_index: Zero-based index of the question to retrieve (0–9).

    Returns:
        A dict representing the Question_Dict (7 keys: ``id``, ``category``,
        ``question``, ``ideal_keywords``, ``difficulty``, ``follow_ups``,
        ``scoring_hint``) if the row exists, or ``None`` if no matching
        row is found.

    Raises:
        sqlite3.Error: On any database error.
    """
    conn = _get_connection()
    conn.row_factory = sqlite3.Row
    cursor = conn.execute(
        "SELECT data FROM questions WHERE session_id = ? AND q_index = ?",
        (session_id, q_index),
    )
    row = cursor.fetchone()
    conn.close()
    if row is None:
        return None
    return json.loads(row["data"])


def get_report(session_id: str) -> dict | None:
    """Retrieve the saved final report for a session.

    Looks up the ``reports`` table by ``session_id`` and JSON-deserializes
    the stored data.

    Args:
        session_id: UUID string identifying the owning session.

    Returns:
        A dict representing the Report_Dict (11 keys) if the row exists,
        or ``None`` if no report has been saved for this session.

    Raises:
        sqlite3.Error: On any database error.
    """
    conn = _get_connection()
    conn.row_factory = sqlite3.Row
    cursor = conn.execute(
        "SELECT data FROM reports WHERE session_id = ?",
        (session_id,),
    )
    row = cursor.fetchone()
    conn.close()
    if row is None:
        return None
    return json.loads(row["data"])


def get_follow_up_count(session_id: str, q_index: int) -> int:
    """Return the current follow-up count for a specific question.

    Queries the ``follow_up_tracking`` table.  If no row exists for the
    given ``(session_id, q_index)`` pair, returns 0 (indicating no
    follow-ups have been asked yet).

    Args:
        session_id: UUID string identifying the owning session.
        q_index: Zero-based index of the question (0–9).

    Returns:
        An integer representing the number of follow-up questions already
        asked for this question.  Returns 0 if no tracking row exists.

    Raises:
        sqlite3.Error: On any database error.
    """
    conn = _get_connection()
    conn.row_factory = sqlite3.Row
    cursor = conn.execute(
        "SELECT count FROM follow_up_tracking WHERE session_id = ? AND q_index = ?",
        (session_id, q_index),
    )
    row = cursor.fetchone()
    conn.close()
    if row is None:
        return 0
    return row["count"]


def increment_follow_up_count(session_id: str, q_index: int) -> None:
    """Insert or increment the follow-up count for a specific question.

    Uses an upsert pattern: if no row exists for the given
    ``(session_id, q_index)``, inserts a new row with ``count=1``.
    If a row already exists, increments the existing count by 1.

    Args:
        session_id: UUID string identifying the owning session.
        q_index: Zero-based index of the question (0–9).

    Returns:
        None

    Raises:
        sqlite3.Error: On any database error.
    """
    conn = _get_connection()
    with conn:
        conn.execute(
            """
            INSERT INTO follow_up_tracking (session_id, q_index, count)
            VALUES (?, ?, 1)
            ON CONFLICT(session_id, q_index)
            DO UPDATE SET count = count + 1
            """,
            (session_id, q_index),
        )
    conn.close()


def reset_follow_up_count(session_id: str, q_index: int) -> None:
    """Reset the follow-up count for a specific question to zero.

    Updates the ``follow_up_tracking`` row for the given
    ``(session_id, q_index)`` to set ``count=0``.  If no row exists
    (i.e. the question has never had a follow-up tracked), this is a
    no-op — no error is raised and no row is inserted.

    Args:
        session_id: UUID string identifying the owning session.
        q_index: Zero-based index of the question (0–9).

    Returns:
        None

    Raises:
        sqlite3.Error: On any database error.
    """
    conn = _get_connection()
    with conn:
        conn.execute(
            "UPDATE follow_up_tracking SET count = 0 WHERE session_id = ? AND q_index = ?",
            (session_id, q_index),
        )
    conn.close()
